from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage
from dotenv import load_dotenv
load_dotenv() 

llm = ChatOpenAI(model="gpt-4o", temperature=0)
print("🤖 ChatOpenAI initialized")

# =========================
# Travel LLM
# =========================
def call_travel_llm(user_details: dict) -> str:
    """
    Generate a concise, actionable travel recommendation using ChatOpenAI LLM.

    This function calls a ChatOpenAI model with a tightly scoped system prompt
    to produce short, practical travel guidance tailored to a specific event.
    The response is optimized for quick consumption and immediate action.

    The LLM output is constrained to:
    - Event-specific and location-aware recommendations
    - Seasonal and weather-informed suggestions inferred from date and place
    - A maximum length suitable for UI display (under ~120 words)

    Args:
        user_details (dict):
            Dictionary containing event context, expected keys:
            - event_location (str): City or destination of the event
            - event_type (str): Type of event (e.g., conference, wedding)
            - event_date (str): Event date or date range

    Returns:
        str:
            A short, structured travel recommendation generated by the LLM.

    Raises:
        Exception:
            Propagates any error raised during LLM invocation for upstream handling.
    """
    print("\n➡️ [LLM] call_travel_llm called")
    print("Payload:", user_details)

    try:
        system = (
            "You are an upbeat, no-fluff travel assistant. Deliver short, tactical suggestions that a "
            "traveler can act on immediately. Focus on the event city and date window; keep answers under "
            "120 words.\n"
            "- Cover: best areas to stay (1-2), 2-3 must-do sights/food, quick transit tips, and 1 weather/packing note.\n"
            "- Tailor to the event type (e.g., wedding, conference, festival) and the location season.\n"
            "- Infer season and typical weather from the date/location; adjust suggestions for the place type "
            "(urban, beach, mountain, countryside) when obvious.\n"
            "- If details are missing, make sensible defaults and continue; never ask the user for more info.\n"
            "- No lists longer than 4 items; no emojis; avoid generic filler."
        )
        user = f"""
Location: {user_details["event_location"]}
Event: {user_details["event_type"]}
Date: {user_details["event_date"]}
"""

        response = llm.invoke([
            SystemMessage(content=system),
            HumanMessage(content=user)
        ])

        print("⬅️ [LLM] response received")
        print(response.content)
        return response.content

    except Exception as e:
        print("❌ ERROR in call_travel_llm")
        print(e)
        raise
